### ISSUE TITLE
m2e lifecycle execution mapping

### ISSUE THREAD

**Issue by janssepe** [GeoDienstenCentrum/sass-maven-plugin#74] opened 2015-09-04 06:50 UTC
Hi,

I was wondering if you could add [m2e lifecycle execution mapping](https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html) to the plugin.

**Comment by mprins** [comment] 2015-09-04 11:16
As I noted in #10 I no longer use Eclipse (so I can't/won't test) but a pull request providing this is welcome.

**Comment by mprins** [comment] 2015-09-15 09:47
closing this as a duplicate of #10

**Closed by mprins** 2015-09-15 09:47 UTC
Labels: duplicate, help wanted, question

**Comment by mprins** [comment] 2016-05-27 15:10
A PR was received, so this will be in the next release
see #110
