### ISSUE TITLE
requires Maven version 3.2.5

### ISSUE THREAD

**Issue by ChinesePeanuts** [GeoDienstenCentrum/sass-maven-plugin#134] opened 2016-10-10 15:24 UTC
Hi,

I have a strange issue with the plugin.
So I have this message when I tried to build : 
`Caused by: org.apache.maven.plugin.PluginIncompatibleException: The plugin nl.geodienstencentrum.maven:sass-maven-plugin:2.21 requires Maven version 3.2.5`

But the thing is, this is what I get when I check the maven version with `mvn --version` :
`Apache Maven 3.3.9`
`Maven home: /usr/share/maven`
`Java version: 1.8.0_102, vendor: Oracle Corporation`
`Java home: /usr/lib/jvm/oracle-java8-jdk-amd64/jre`
`Default locale: en_US, platform encoding: UTF-8`
`OS name: "linux", version: "4.7.0-1-amd64", arch: "amd64", family: "unix"`

Here is what I have about the plugin in my pom.xml :

`<plugin>`
    `<groupId>nl.geodienstencentrum.maven</groupId>`
    `<artifactId>sass-maven-plugin</artifactId>`
    `<version>2.21</version>`
    `<executions>`
        `<execution>`
            `<phase>package</phase>`
            `<goals>`
                `<goal>update-stylesheets</goal>`
            `</goals>`
        `</execution>`
    `</executions>`
    `<configuration>`
        `<sassSourceDirectory>`
            `${basedir}/src/main/webapp/assets/scss`
        `</sassSourceDirectory>`
        `<destination>`
            `${project.build.directory}/TEST/`
        `</destination>`
    `</configuration>`
`</plugin>`

`<dependency>`
`<groupId>nl.geodienstencentrum.maven</groupId>`
`<artifactId>sass-maven-plugin</artifactId>`
`<version>2.21</version>`
`</dependency>`

So here is what I tried, I removed the `<prerequesite>` from the `sass-maven-plugin-2.21.pom` and it actually worked.

So what am I missing ?

Thanks in advance for your help.

**Comment by mprins** [comment] 2016-10-10 18:10
Running your build with `-X` will probably show us what is wrong with your config.

**Comment by mprins** [comment] 2016-10-11 08:34
closing as I have been unable to reproduce this and no debugging info has been provided

proof that this works fine on both win64 (appveyor) and linux64 (travis-ci):
  - https://ci.appveyor.com/project/mprins/maven-compass-example/build/98%20(sass-maven-plugin-2.21)
  - https://travis-ci.org/mprins/maven-compass-example/builds/166674403

**Closed by mprins** 2016-10-11 08:34 UTC
Labels: invalid

**Comment by ChinesePeanuts** [comment] 2016-10-11 08:46
Hi,
Thanks for your quick answer, actually by reading you, I just noticed that the project was not using the same version installed on my computer, but an older one.
Sorry for bothering you, my bad.
