### ISSUE TITLE
CSS files(duplicate) generated under both destination and source directories 

### ISSUE THREAD

**Issue by Srikanth-GitHub** [GeoDienstenCentrum/sass-maven-plugin#122] opened 2016-07-12 20:48 UTC
### Environment and configuration

* Maven version 3.3.9
* Java version 1.8.0_66
* Operating system and platform OS X El Capitan (Version: 10.11.2)

### Maven configuration

    <plugin><groupId>nl.geodienstencentrum.maven</groupId>
    <artifactId>sass-maven-plugin</artifactId>
    <version>2.20</version>

    <configuration>

        <sassOptions>
            <unix_newlines>true</unix_newlines>
            <cache>true</cache>
            <always_update>true</always_update>
            <style>:expanded</style>
            <sourcemap>:none</sourcemap>
        </sassOptions>

        <resources>
            <resource>
                <source>
                    <directory>${basedir}/src/main/content/jcr_root/etc</directory>
                    <includes>
                        <include>/**/scss</include>
                    </includes>
                </source>
                <relativeOutputDirectory>../css</relativeOutputDirectory>
                <destination>${basedir}/src/main/content/jcr_root/etc/</destination>
            </resource>
        </resources>
        
    </configuration>
    
    <executions>
        <execution>
            <id>generate-css</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>update-stylesheets</goal>
            </goals>
        </execution>
    </executions></plugin>

### Assumption
Assuming I have "test.scss" file under(i.e. Source) "${basedir}/src/main/content/jcr_root/etc/.../scss"

### Expected Behavior

Plugin should generate "test.css" file only under(i.e Destination) "${basedir}/src/main/content/jcr_root/etc/.../css"

### Actual Behavior

"test.css" file got created both under(i.e Destination) "${basedir}/src/main/content/jcr_root/etc/.../css" as well as under(i.e Source) "${basedir}/src/main/content/jcr_root/etc/.../scss"

**Comment by mprins** [comment] 2016-07-20 02:38
Please provide a concrete case not an imaginary case to reproduce this

**Comment by Srikanth-GitHub** [comment] 2016-07-20 19:43
It's not imaginary case its happening in realtime with the above configuration. The css files are getting generated twice under source and destination directories, it should create only under destination directory. Am I configuring something wrong here? As per my requirement source and destination relative paths are same but in different folders.

concrete case in the sense, please let me know what exactly you are expecting from me?

**Comment by igromanru** [comment] 2016-07-22 07:45
I guess your configuration is wrong.  
Try this:  
```
<resources>
	<resource>
		<source>
			<directory>${basedir}/src/main/content/jcr_root/etc/scss</directory>
			<includes>
				<include>**/*.scss</include>
			</includes>
		</source>
		<relativeOutputDirectory>../css</relativeOutputDirectory>
		<destination>${basedir}/src/main/content/jcr_root/etc/css</destination>
	</resource>
</resources>
```
This should generate from your `/src/main/content/jcr_root/etc/scss/(folder)/test.scass` a `/src/main/content/jcr_root/etc/css/(folder)/test.css`

**Comment by Srikanth-GitHub** [comment] 2016-07-27 16:56
Thanks for your reply.
My project scss source folder structure is something like this
${basedir}/src/main/content/jcr_root/etc
under this "${basedir}/src/main/content/jcr_root/etc" some where scss files will be present under scss folders( like "/**/scss/xxx.scss").
My requirement is, css files should be generated under the same folder structure as source but under separate folder called css(just besides the scss folder like /**/css/xxx.css). So I configured like above. It's working exactly as I expected. But it's generating css files under both css and scss folders unnecessary (Ideally it should generate under css folder only).

As you said I have configured below.

<configuration>
                            <sassOptions>
                                <unix_newlines>true</unix_newlines>
                                <cache>true</cache>
                                <always_update>true</always_update>
                                <style>:expanded</style>
                                <sourcemap>:none</sourcemap>
                            </sassOptions>
                            
                            <resources>
                                <resource>
                                    <source>
                                        <directory>${basedir}/src/main/content/jcr_root/etc</directory>
                                        <includes>
                                            <include>/**/*.scss</include>
                                        </includes>
                                    </source>
                                    <relativeOutputDirectory>../css</relativeOutputDirectory>
                                    <destination>${basedir}/src/main/content/jcr_root/etc</destination>
                                </resource>
                            </resources>
</configuration>

If I configure <include>**/*.scss</include>, instead of <include>**/scss</include>
<relativeOutputDirectory>../css</relativeOutputDirectory> was simply ignored.
I mean, css files under css folder are not getting generated. They are generated besides scss file under scss folder.

**Comment by mprins** [comment] 2016-07-28 08:15
> concrete case in the sense, please let me know what exactly you are expecting from me?

a sample project (eg. github repo) for us to reproduce this, you case is imaginary because you have file paths with 3 dots; no such thing exists

**Comment by mprins** [comment] 2016-08-31 09:19
closing as no sample project to reproduce this has been provided

**Closed by mprins** 2016-08-31 09:19 UTC
Labels: invalid
