### ISSUE TITLE
Parallel build of multi module reactor with option -T 1C causes build failure indeterministically on Windows

### ISSUE THREAD

**Issue by ajgassner** [GeoDienstenCentrum/sass-maven-plugin#148] opened 2017-03-14 13:18 UTC
### Environment and configuration
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Java version: 1.8.0_51, vendor: Oracle Corporation
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```
<plugin>
	<groupId>nl.geodienstencentrum.maven</groupId>
	<artifactId>sass-maven-plugin</artifactId>
	<executions>
		<execution>
			<id>compile-scss-to-css</id>
			<phase>generate-resources</phase>
			<goals>
				<goal>update-stylesheets</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<sassSourceDirectory>${basedir}/src/main/theme</sassSourceDirectory>
		<destination>${project.build.directory}/theme-generated</destination>
		<sassOptions>
			<style>:compressed</style>
			<always_update>true</always_update>
			<sourcemap>:none</sourcemap>
		</sassOptions>
	</configuration>
</plugin>
```
### Expected Behavior
The plugin should support parallel builds.

### Actual Behavior
The plugin doesn't seem to support parallel builds. Sometimes the same build fails with different problem descriptions, e.g.

```
Failed to execute goal nl.geodienstencentrum.maven:sass-maven-plugin:2.23:update-stylesheets (compile-scss-to-css) on project ...: Execution compile-scss-to-css of goal nl.geodienstencentrum.maven:sass-maven-plugin:2.23:update-stylesheets failed: (SystemCallError) Unknown error - channel: org.jruby.util.io.ChannelFD@47e3ba5a uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/ffi/platform/x86_64-windows/platform.conf
```
or
```
Execution compile-scss-to-css of goal nl.geodienstencentrum.maven:sass-maven-plugin:2.23:update-stylesheets failed: (LoadError) library `java' could not be loaded: java.lang.IllegalStateException: zip file closed
```

**Comment by mprins** [comment] 2017-03-15 16:10
All the integration are run test using `-T2` on AppVeyor/Windows 2012 (as well as macos/linux) without these kind of problems and both provided traces suggest this problem is related to jruby, not the plugin code. Not having a windows machine basically makes it impossible to debug or reproduce

**Comment by ajgassner** [comment] 2017-03-15 17:30
The Sass plugin itself is no multi-module maven project. The problem occurs when multiple modules gets compiled concurrently.

**Comment by mprins** [comment] 2017-03-16 10:58
I have a multimodule project[0] that builds just fine using `-T2.2C` on a dual-quadcore linux machine. 
You could see if the 2.24-SNAPSHOT works better for you, it has a newer jruby runtime

[0] https://sourceforge.net/p/dokuwikispatial/code/HEAD/tree/trunk/

**Comment by ajgassner** [comment] 2017-03-16 19:12
Same with 2.24-SNAPSHOT. About 2 of 10 builds are failing in average. What about https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/src/main/java/nl/geodienstencentrum/maven/plugin/sass/AbstractSassMojo.java#L233

Would ```LocalContextScope.THREADSAFE``` make more sense?

> Known as the "apartment thread model", this mode makes ScriptingContainer lazily creates a runtime and a variable map separately for each calling thread. Therefore, despite the fact that multiple threads call on the same object, they are completely isolated from each other. (the flip side of the coin is that no ruby objects can be shared between threads as they belong to different "ruby VM".)

**Comment by mprins** [comment] 2017-03-17 08:56
No, because the scripting container is a local, method, variable. It is created and discarded in the method call, so each call will have an isolated scriptingcontainer to do the work.

**Comment by ajgassner** [comment] 2017-03-17 09:20
Yes, in the plugin's Java code. But is it possible that multiple JRuby runtimes behind share data? If this is the case the method executeSassScript needs to be synchronized. But my understanding is that ```LocalContextScope.THREADSAFE``` avoids the use of the bad performing synchonization.

This are only assuptions, unfortunately I don't have any experience with JRuby.

**Comment by mprins** [comment] 2017-05-27 14:11
This probably a memory issue like #149 and unlikely to be fixable in our code. 
Closing because not reproducible, even by reporter

**Closed by mprins** 2017-05-27 14:11 UTC
Labels: bug, incomplete report, JRuby, windows
