### ISSUE TITLE
Allow --sourcemap=none option to work

### ISSUE THREAD

**Issue by jepsar** [GeoDienstenCentrum/sass-maven-plugin#99] opened 2016-02-18 21:25 UTC
According to [this answer on StackOverflow](http://stackoverflow.com/a/30155930/880619) you cannot to combine `--sourcemap=none` with `--update` or (in comments) you need to add `--force`. This might be the reason I can't disable source maps. I can't find any option to get this working. Here is what I've tried:

````
	<plugin>
		<groupId>nl.geodienstencentrum.maven</groupId>
		<artifactId>sass-maven-plugin</artifactId>
		<version>2.15</version>
		<executions>
			<execution>
				<phase>prepare-package</phase>
				<goals>
					<goal>update-stylesheets</goal>
				</goals>
				<configuration>
					<resources>
						<resource>
							<source>
								<directory>${basedir}/src/main/resources</directory>
								<includes>
									<include>**/*.scss</include>
								</includes>
							</source>
							<destination>${basedir}/target/classes</destination>
						</resource>
					</resources>
					<sassOptions>
						<sourcemap>'none'</sourcemap>
					</sassOptions>
				</configuration>
			</execution>
		</executions>
	</plugin>
````

**Comment by mprins** [comment] 2016-02-19 15:44
duplicate of #45

**Closed by mprins** 2016-02-19 15:44 UTC
Labels: invalid

**Comment by jepsar** [comment] 2016-02-19 16:21
Clear. Thank you!
